package lightoff_maumejean_version_console;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MAUMEJEAN DENIS
 */
public class FenetrePrincipale extends javax.swing.JFrame {
    GrilleDeJeu grille;
    int nbCoups;
    int i;
    int nbLignes = 10;
    int nbColonnes = 10;
    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, nbColonnes*40, nbLignes*40));
        this.pack();
        this.revalidate();
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        this.grille = new GrilleDeJeu(nbLignes, nbColonnes);
        
        for (int i=0; i < nbLignes; i++) {
            for (int j=0; j < nbColonnes; j++ ) {
                CelluleGraphique bouton_cellule = new CelluleGraphique( grille.matriceCellules[i][j], 36,36);
                PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
            }
        
        
        }
        
        PanneauBoutonsVerticaux.setLayout(new GridLayout(nbLignes, 1));
        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1 * 40, nbLignes * 40));
        this.pack();
        this.revalidate();
        
        PanneauBoutonsHorizontaux.setLayout(new GridLayout(1, nbColonnes)); // Inverser les arguments pour avoir 1 ligne et plusieurs colonnes
        getContentPane().add(PanneauBoutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, nbColonnes * 40, 1 * 40)); // Ajuster les dimensions pour la grille horizontale
        this.pack();
        this.revalidate();

        
        // création du panneau de boutons verticaux (pour les lignes)
        for (i = 0; i < nbLignes; i++) {
            JButton bouton_ligne = new JButton();
            ActionListener ecouteurClick = new ActionListener() {
                final int j = i;
                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerLigneDeCellules(j);
                    jProgressBar1.setMaximum(nbLignes*nbColonnes);
                    jProgressBar1.setMinimum(0);
                    int nbrCellulesetteinte = nbLignes*nbColonnes - grille.combiendecellulesencoreallumés();
                    jProgressBar1.setValue(nbrCellulesetteinte);
                    repaint();
                }
            };
            bouton_ligne.addActionListener(ecouteurClick);
            PanneauBoutonsVerticaux.add(bouton_ligne);
        }
        
        for (i = 0; i < nbColonnes; i++) {
            JButton bouton_Colonnes = new JButton();
            ActionListener ecouteurClick = new ActionListener() {
                final int j = i;
                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerColonneDeCellules(j);
                    jProgressBar1.setMaximum(nbLignes*nbColonnes);
                    jProgressBar1.setMinimum(0);
                    int nbrCellulesetteinte = nbLignes*nbColonnes - grille.combiendecellulesencoreallumés();
                    jProgressBar1.setValue(nbrCellulesetteinte);
                    repaint();
                }
            };
            bouton_Colonnes.addActionListener(ecouteurClick);
            PanneauBoutonsHorizontaux.add(bouton_Colonnes);
        }

    }
    
    public void initialiserPartie() {
        grille.eteindreToutesLesCellules();
        grille.melangerMatriceAleatoirement(10);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDiag1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        PanneauBoutonsVerticaux = new javax.swing.JPanel();
        PanneauBoutonsHorizontaux = new javax.swing.JPanel();
        btnDiag2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(102, 102, 255));
        PanneauGrille.setPreferredSize(new java.awt.Dimension(360, 360));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 400, 400));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 200, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 480, -1));

        btnDiag1.setBackground(new java.awt.Color(255, 255, 105));
        btnDiag1.setText("\\");
            btnDiag1.setPreferredSize(new java.awt.Dimension(40, 40));
            btnDiag1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDiag1ActionPerformed(evt);
                }
            });
            getContentPane().add(btnDiag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

            jProgressBar1.setForeground(new java.awt.Color(0, 153, 255));
            jProgressBar1.setOrientation(1);
            jProgressBar1.setOpaque(true);
            jProgressBar1.setPreferredSize(new java.awt.Dimension(40, 200));
            getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 20, 390));

            PanneauBoutonsVerticaux.setBackground(new java.awt.Color(204, 204, 255));

            javax.swing.GroupLayout PanneauBoutonsVerticauxLayout = new javax.swing.GroupLayout(PanneauBoutonsVerticaux);
            PanneauBoutonsVerticaux.setLayout(PanneauBoutonsVerticauxLayout);
            PanneauBoutonsVerticauxLayout.setHorizontalGroup(
                PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 40, Short.MAX_VALUE)
            );
            PanneauBoutonsVerticauxLayout.setVerticalGroup(
                PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
            );

            getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 400));

            PanneauBoutonsHorizontaux.setBackground(new java.awt.Color(204, 204, 255));

            javax.swing.GroupLayout PanneauBoutonsHorizontauxLayout = new javax.swing.GroupLayout(PanneauBoutonsHorizontaux);
            PanneauBoutonsHorizontaux.setLayout(PanneauBoutonsHorizontauxLayout);
            PanneauBoutonsHorizontauxLayout.setHorizontalGroup(
                PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
            );
            PanneauBoutonsHorizontauxLayout.setVerticalGroup(
                PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 40, Short.MAX_VALUE)
            );

            getContentPane().add(PanneauBoutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 400, 40));

            btnDiag2.setBackground(new java.awt.Color(255, 255, 105));
            btnDiag2.setText("/");
            btnDiag2.setPreferredSize(new java.awt.Dimension(40, 40));
            btnDiag2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDiag2ActionPerformed(evt);
                }
            });
            getContentPane().add(btnDiag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 40));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnDiag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiag1ActionPerformed
        this.grille.activerDiagonaleDescendante();
        int nbrCellulesetteinte = nbLignes*nbColonnes - grille.combiendecellulesencoreallumés();
        jProgressBar1.setValue(nbrCellulesetteinte);
        repaint();
    }//GEN-LAST:event_btnDiag1ActionPerformed

    private void btnDiag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiag2ActionPerformed

        this.grille.activerDiagonaleMontante();
        jProgressBar1.setMaximum(nbLignes*nbColonnes);
        jProgressBar1.setMinimum(0);
        int nbrCellulesetteinte = nbLignes*nbColonnes - grille.combiendecellulesencoreallumés();
        jProgressBar1.setValue(nbrCellulesetteinte);
        repaint();
    }//GEN-LAST:event_btnDiag2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauBoutonsHorizontaux;
    private javax.swing.JPanel PanneauBoutonsVerticaux;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton btnDiag1;
    private javax.swing.JButton btnDiag2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
